config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  root 'pages#home'

  resources :courses do
    resources :lessons do
      resources :tasks
    end

    member do
      post 'enroll', to: 'courses#enroll'
    end
  end

  get "my_courses", to: "courses#my_courses"

  resources :submissions
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppTraining</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <%= link_to 'Home', root_path, class: 'navbar-brand' %>
        </div>
      </nav>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <li class="nav-link">
            <%= link_to 'Courses', courses_path, class: 'nav-link active' %>
          <li class="nav-item">
            <% if current_user %>
            <li class="nav-link">
              <%= link_to "My courses", my_courses_path, class: "nav-link active" %>
            </li>
        </ul>
            <!-- app/views/layouts/application.html.erb -->
            <form class="d-flex" role="search" action="<%= courses_path(q: true) %>" method="get">
              <input class="form-control me-2" type="search" name="q[title_cont]" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success me-2" type="submit">Search</button>
            </form>
            </div>


    <li class="nav-link me-2">
      <div class="toast-body">Hello <%= current_user.email %>!</div>
      <div class="toast-body">You are a <%= current_user.role %></div>
      <% if current_user.admin? %>
          <li class="nav-link">Users: <%= User.count %></li>
          </li>
        <% end %>
        <li class="nav-link">
          <%= link_to 'Sign out', destroy_user_session_path, 'data-turbo-action': 'submit', 'data-turbo-frame': '_top', method: :delete, class: 'btn btn-danger' %>
        </li>
      <% else %>
        <li class="nav-link">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' %>
        </li>
        <li class="nav-link">
          <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary' %>
        </li>
        <% end %>
    </div>
  </nav>

  <%= yield %>
  </body>
</html>